# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY WeatherTracker/*.csproj ./
RUN dotnet restore

# Copy the remaining files and build the app
COPY . ./
RUN dotnet publish -c Release -o out

# Stage 2: Run the application
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

RUN sed -i "s/__API_KEY__/${WEATHER_API_KEY}/" appsettings.json

# Set the entry point for the application
ENTRYPOINT ["dotnet", "WeatherTracker.dll"]
